apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-continuum.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ghost-continuum
  ports:
    - name: hub
      port: {{ .Values.service.hubPort }}
      targetPort: hub
    - name: ghost-lan
      port: {{ .Values.service.ghostLanPort }}
      targetPort: ghost-lan
    - name: edge
      port: {{ .Values.service.edgePort }}
      targetPort: edge